### ISSUE TITLE
feature request: support `Map`

### ISSUE THREAD

**Issue by trim21** [steelbrain/php-serialize#291] opened 2023-01-01 23:22 UTC
there is no way to serialize a object to int keys like php, js object's keys are always string.

it's possible to present it in js with `new Map([[1,'q']])` and hopefully is will became `a:1:{i:1;s:1:"q";}`

**Comment by miso-belica** [comment] 2023-04-28 09:25
Hello, would be nice to consider this addition because there is currently a problem with the order of unserialized array. JS orders numbers in `Object` by their value when iterating but PHP preserves insertion order. Using Map would solve this problem. For example as and extra option to use it or as a breaking change. The problem is at line 63 in https://github.com/steelbrain/php-serialize/blob/1c75a879bf11757d4ae002ab35e4171864e5bd58/src/unserialize.ts#L60-L67

```ts
  // this test fails currently
  it('orders correctly', async () => {
    const d1 = unserialize('a:4:{i:5;i:1;i:4;i:2;i:3;i:3;i:2;i:4;}');
    expect(Object.values(d1)).toEqual([1, 2, 3, 4]);
  });
```

```ts
  // I imagine something like this if you don't want to introduce a new major version with backward incompatibility
  // this is just one of many possibilities, important is to get ordered items back
  it('orders correctly using map', async () => {
    const d1 = unserialize('a:4:{i:5;i:1;i:4;i:2;i:3;i:3;i:2;i:4;}', {}, {toObject: 'object' | 'map' | 'pairs'});
    expect([...d1.values()]).toEqual([1, 2, 3, 4]);
  });
```

I see there is a PR https://github.com/steelbrain/php-serialize/pull/292 already to support `Map`. Maybe it could be incorporated there?

**Comment by steelbrain** [comment] 2023-04-30 10:45
Fixed by https://github.com/steelbrain/php-serialize/pull/292

**Closed by steelbrain** 2023-04-30 10:45 UTC
